/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokemon;

import exercicopokemon.Batalha;
import exercicopokemon.Pokemon;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author limal
 */
public class pokebola extends javax.swing.JFrame {

    /**
     * Creates new form pokebola
     */
    public pokebola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPokemon = new javax.swing.JComboBox<>();
        cbxPokemon1 = new javax.swing.JComboBox<>();
        imagemm1 = new javax.swing.JLabel();
        imagem2 = new javax.swing.JLabel();
        btnLutar = new javax.swing.JButton();
        imagemm2 = new javax.swing.JLabel();
        lblImprimirPokemonNome = new javax.swing.JLabel();
        lblImprimirPokemonTipo = new javax.swing.JLabel();
        lblImprimirPokemonNivel = new javax.swing.JLabel();
        lblImprimirPokemonVida = new javax.swing.JLabel();
        lblImprimirPokemonAtaque = new javax.swing.JLabel();
        lblImprimirPokemonDefesa = new javax.swing.JLabel();
        lblImprimirPokemonVelocidade = new javax.swing.JLabel();
        lblImprimirPokemonTipo1 = new javax.swing.JLabel();
        lblImprimirPokemonNivel1 = new javax.swing.JLabel();
        lblImprimirPokemonVida1 = new javax.swing.JLabel();
        lblImprimirPokemonAtaque1 = new javax.swing.JLabel();
        lblImprimirPokemonDefesa1 = new javax.swing.JLabel();
        lblImprimirPokemonVelocidade1 = new javax.swing.JLabel();
        lblImprimirPokemonNome1 = new javax.swing.JLabel();
        lblImprimirPokemonNome2 = new javax.swing.JLabel();
        lblImprimirPokemonTipo2 = new javax.swing.JLabel();
        lblImprimirPokemonNivel2 = new javax.swing.JLabel();
        lblImprimirPokemonVida2 = new javax.swing.JLabel();
        lblImprimirPokemonAtaque2 = new javax.swing.JLabel();
        lblImprimirPokemonDefesa2 = new javax.swing.JLabel();
        lblImprimirPokemonVelocidade2 = new javax.swing.JLabel();
        lblImprimirPokemonNome3 = new javax.swing.JLabel();
        lblImprimirPokemonTipo3 = new javax.swing.JLabel();
        lblImprimirPokemonNivel3 = new javax.swing.JLabel();
        lblImprimirPokemonVida3 = new javax.swing.JLabel();
        lblImprimirPokemonAtaque3 = new javax.swing.JLabel();
        lblImprimirPokemonDefesa3 = new javax.swing.JLabel();
        lblImprimirPokemonVelocidade3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPokemon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Squirtle", "Treecko", "Emboar ", "Golem" }));
        cbxPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        cbxPokemon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Greninja", "Meganium", "Onix", "Blaziken" }));
        cbxPokemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemon1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPokemon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));
        getContentPane().add(imagemm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 220, 190));
        getContentPane().add(imagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 180));

        btnLutar.setText("LUTAR");
        btnLutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        imagemm2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imagemm2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(imagemm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 240, 170));
        getContentPane().add(lblImprimirPokemonNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        getContentPane().add(lblImprimirPokemonTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));
        getContentPane().add(lblImprimirPokemonNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));
        getContentPane().add(lblImprimirPokemonVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));
        getContentPane().add(lblImprimirPokemonAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));
        getContentPane().add(lblImprimirPokemonDefesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));
        getContentPane().add(lblImprimirPokemonVelocidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        lblImprimirPokemonTipo1.setText("Tipo");
        getContentPane().add(lblImprimirPokemonTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblImprimirPokemonNivel1.setText("Nível");
        getContentPane().add(lblImprimirPokemonNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lblImprimirPokemonVida1.setText("Vida");
        getContentPane().add(lblImprimirPokemonVida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lblImprimirPokemonAtaque1.setText("Ataque");
        getContentPane().add(lblImprimirPokemonAtaque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblImprimirPokemonDefesa1.setText("Defesa");
        getContentPane().add(lblImprimirPokemonDefesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        lblImprimirPokemonVelocidade1.setText("Velocidade");
        getContentPane().add(lblImprimirPokemonVelocidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        lblImprimirPokemonNome1.setText("Nome");
        getContentPane().add(lblImprimirPokemonNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblImprimirPokemonNome2.setText("Nome");
        getContentPane().add(lblImprimirPokemonNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        lblImprimirPokemonTipo2.setText("Tipo");
        getContentPane().add(lblImprimirPokemonTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        lblImprimirPokemonNivel2.setText("Nível");
        getContentPane().add(lblImprimirPokemonNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        lblImprimirPokemonVida2.setText("Vida");
        getContentPane().add(lblImprimirPokemonVida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        lblImprimirPokemonAtaque2.setText("Ataque");
        getContentPane().add(lblImprimirPokemonAtaque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        lblImprimirPokemonDefesa2.setText("Defesa");
        getContentPane().add(lblImprimirPokemonDefesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        lblImprimirPokemonVelocidade2.setText("Velocidade");
        getContentPane().add(lblImprimirPokemonVelocidade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));
        getContentPane().add(lblImprimirPokemonNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));
        getContentPane().add(lblImprimirPokemonTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));
        getContentPane().add(lblImprimirPokemonNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));
        getContentPane().add(lblImprimirPokemonVida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));
        getContentPane().add(lblImprimirPokemonAtaque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));
        getContentPane().add(lblImprimirPokemonDefesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));
        getContentPane().add(lblImprimirPokemonVelocidade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/f6a18ac56651ce4f9ca7e0230706a0b6.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -620, 718, 1030));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemonActionPerformed
        if (cbxPokemon.getSelectedIndex() == 0){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon1.gif"));
            imagemm1.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm1.getWidth(),imagemm1.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Squirtle", "Agua", 10);
            lblImprimirPokemonNome.setText(p1.getNome());
            lblImprimirPokemonTipo.setText(p1.getTipo());
            lblImprimirPokemonNivel.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade.setText(String.valueOf(p1.getVelocidade()));
        } 
        if (cbxPokemon.getSelectedIndex() == 1){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Treecko.gif"));
            imagemm1.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm1.getWidth(),imagemm1.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Treecko", "Planta", 25);
            lblImprimirPokemonNome.setText(p1.getNome());
            lblImprimirPokemonTipo.setText(p1.getTipo());
            lblImprimirPokemonNivel.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade.setText(String.valueOf(p1.getVelocidade()));
        }
        if (cbxPokemon.getSelectedIndex() == 2){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/embore.gif"));
            imagemm1.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm1.getWidth(),imagemm1.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Emboar", "Fogo", 39);
            lblImprimirPokemonNome.setText(p1.getNome());
            lblImprimirPokemonTipo.setText(p1.getTipo());
            lblImprimirPokemonNivel.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade.setText(String.valueOf(p1.getVelocidade()));
        }
        if (cbxPokemon.getSelectedIndex() == 3){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Golem.gif"));
            imagemm1.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm1.getWidth(),imagemm1.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Golem", "Pedra", 40);
            lblImprimirPokemonNome.setText(p1.getNome());
            lblImprimirPokemonTipo.setText(p1.getTipo());
            lblImprimirPokemonNivel.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade.setText(String.valueOf(p1.getVelocidade()));
        }
    }//GEN-LAST:event_cbxPokemonActionPerformed

    private void imagemm2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imagemm2AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imagemm2AncestorAdded

    private void cbxPokemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemon1ActionPerformed
        if (cbxPokemon1.getSelectedIndex() == 0){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Greninja.gif"));
            imagemm2.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm2.getWidth(),imagemm2.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Greninja", "Agua", 37);
            lblImprimirPokemonNome3.setText(p1.getNome());
            lblImprimirPokemonTipo3.setText(p1.getTipo());
            lblImprimirPokemonNivel3.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida3.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque3.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa3.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade3.setText(String.valueOf(p1.getVelocidade()));
        }
        if (cbxPokemon1.getSelectedIndex() == 1){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Meganium.gif"));
            imagemm2.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm2.getWidth(),imagemm2.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Meganium", "Planta", 46);
            lblImprimirPokemonNome3.setText(p1.getNome());
            lblImprimirPokemonTipo3.setText(p1.getTipo());
            lblImprimirPokemonNivel3.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida3.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque3.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa3.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade3.setText(String.valueOf(p1.getVelocidade()));
        }
        if (cbxPokemon1.getSelectedIndex() == 2){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Onix.gif"));
            imagemm2.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm2.getWidth(),imagemm2.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Onix", "Pedra", 50);
            lblImprimirPokemonNome3.setText(p1.getNome());
            lblImprimirPokemonTipo3.setText(p1.getTipo());
            lblImprimirPokemonNivel3.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida3.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque3.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa3.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade3.setText(String.valueOf(p1.getVelocidade()));
        }
        if (cbxPokemon1.getSelectedIndex() == 3){
            ImageIcon image = new ImageIcon(getClass().getResource("/resources/Blaziken.gif"));
            imagemm2.setIcon(new ImageIcon(image.getImage().getScaledInstance(imagemm2.getWidth(),imagemm2.getHeight(), Image.SCALE_DEFAULT)));
            Pokemon p1 = new Pokemon("Blaiziken", "Fogo", 36);
            lblImprimirPokemonNome3.setText(p1.getNome());
            lblImprimirPokemonTipo3.setText(p1.getTipo());
            lblImprimirPokemonNivel3.setText(String.valueOf(p1.getNivel()));
            lblImprimirPokemonVida3.setText(String.valueOf(p1.getVida()));
            lblImprimirPokemonAtaque3.setText(String.valueOf(p1.getAtaque()));
            lblImprimirPokemonDefesa3.setText(String.valueOf(p1.getDefesa()));
            lblImprimirPokemonVelocidade3.setText(String.valueOf(p1.getVelocidade()));
        }    }//GEN-LAST:event_cbxPokemon1ActionPerformed

    private void btnLutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutarActionPerformed
        Pokemon p1 = new Pokemon(lblImprimirPokemonNome.getText(), lblImprimirPokemonTipo.getText(), Integer.parseInt(lblImprimirPokemonNivel.getText()));
        Pokemon p2 = new Pokemon(lblImprimirPokemonNome3.getText(), lblImprimirPokemonTipo3.getText(), Integer.parseInt(lblImprimirPokemonNivel3.getText()));
        Batalha battle = new Batalha();
        battle.meuPokemon(lblImprimirPokemonNome.getText(), p1.getVida(), p1.getAtaque(), p1.getDefesa(), p1.getVelocidade());
        battle.outroPokemon(lblImprimirPokemonNome3.getText(), p2.getVida(), p2.getAtaque(), p2.getDefesa(), p2.getVelocidade());
        battle.startBattle();
    }//GEN-LAST:event_btnLutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pokebola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pokebola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pokebola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pokebola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokebola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLutar;
    private javax.swing.JComboBox<String> cbxPokemon;
    private javax.swing.JComboBox<String> cbxPokemon1;
    private javax.swing.JLabel imagem2;
    private javax.swing.JLabel imagemm1;
    private javax.swing.JLabel imagemm2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImprimirPokemonAtaque;
    private javax.swing.JLabel lblImprimirPokemonAtaque1;
    private javax.swing.JLabel lblImprimirPokemonAtaque2;
    private javax.swing.JLabel lblImprimirPokemonAtaque3;
    private javax.swing.JLabel lblImprimirPokemonDefesa;
    private javax.swing.JLabel lblImprimirPokemonDefesa1;
    private javax.swing.JLabel lblImprimirPokemonDefesa2;
    private javax.swing.JLabel lblImprimirPokemonDefesa3;
    private javax.swing.JLabel lblImprimirPokemonNivel;
    private javax.swing.JLabel lblImprimirPokemonNivel1;
    private javax.swing.JLabel lblImprimirPokemonNivel2;
    private javax.swing.JLabel lblImprimirPokemonNivel3;
    private javax.swing.JLabel lblImprimirPokemonNome;
    private javax.swing.JLabel lblImprimirPokemonNome1;
    private javax.swing.JLabel lblImprimirPokemonNome2;
    private javax.swing.JLabel lblImprimirPokemonNome3;
    private javax.swing.JLabel lblImprimirPokemonTipo;
    private javax.swing.JLabel lblImprimirPokemonTipo1;
    private javax.swing.JLabel lblImprimirPokemonTipo2;
    private javax.swing.JLabel lblImprimirPokemonTipo3;
    private javax.swing.JLabel lblImprimirPokemonVelocidade;
    private javax.swing.JLabel lblImprimirPokemonVelocidade1;
    private javax.swing.JLabel lblImprimirPokemonVelocidade2;
    private javax.swing.JLabel lblImprimirPokemonVelocidade3;
    private javax.swing.JLabel lblImprimirPokemonVida;
    private javax.swing.JLabel lblImprimirPokemonVida1;
    private javax.swing.JLabel lblImprimirPokemonVida2;
    private javax.swing.JLabel lblImprimirPokemonVida3;
    // End of variables declaration//GEN-END:variables
}
